const DEFAULT_ADMIN_VALUE = 1;
const DEFAULT_INVOICING_VALUE = 2;

let AccessProfile = {

    IVOICING: DEFAULT_INVOICING_VALUE,
    INVOICING_AND_ADMIN: [DEFAULT_INVOICING_VALUE, DEFAULT_ADMIN_VALUE],
    ADMIN: DEFAULT_ADMIN_VALUE,

}
export default AccessProfile;