const DEFAULT_ADMIN_VALUE = 1;
const DEFAULT_USER_VALUE = 2;

let AccessProfile = {

    USER: DEFAULT_USER_VALUE,
    USER_AND_ADMIN: [DEFAULT_USER_VALUE, DEFAULT_ADMIN_VALUE],
    ADMIN: DEFAULT_ADMIN_VALUE,

}
export default AccessProfile;