stages:
  - test
  - deploy
  - notification
  - notification-sgbd

análise de código fonte:
  stage: test
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.qualitygate.wait=true
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.sources=.
      -Dsonar.projectBaseDir=.
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.scm.provider=git
      -Dsonar.exclusions=node_modules/*
      -Dsonar.test.exclusions=node_modules/*
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.projectName=$CI_PROJECT_PATH
  allow_failure: true
  only:
    - dev

deploy amb. de desenvolvimento:
  stage: deploy
  script:
    - docker build -t registry.conecthus.org.br/amazon-copy/integracao-mps/v1/backend:dev -f .docker/Dockerfile .
    - docker push registry.conecthus.org.br/amazon-copy/integracao-mps/v1/backend:dev
  allow_failure: false
  only:
    - dev

deploy amb. de teste:
  stage: deploy
  script:
    - docker build -t registry.conecthus.org.br/amazon-copy/integracao-mps/v1/backend:test -f .docker/Dockerfile .
    - docker push registry.conecthus.org.br/amazon-copy/integracao-mps/v1/backend:test
  allow_failure: false
  only:
    - test

deploy amb. de homologação:
  stage: deploy
  script:
    - docker build -t registry.conecthus.org.br/amazon-copy/integracao-mps/v1/backend:hom -f .docker/Dockerfile .
    - docker push registry.conecthus.org.br/amazon-copy/integracao-mps/v1/backend:hom
  allow_failure: false
  only:
    - main

notificação de sucesso por email:
  stage: notification
  script:
    - PROJECT_NAME=$(echo $CI_PROJECT_NAMESPACE | cut -d'/' -f2)
    - domain="$(echo $PROJECT_NAME-$CI_BUILD_REF_NAME | sed 's/-main$//')"
    - sendmail "$GITLAB_USER_LOGIN" "$GITLAB_USER_EMAIL" "[passed] $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME@$CI_BUILD_REF_NAME" "Olá $GITLAB_USER_LOGIN, seu deploy foi realizado com sucesso, seu ambiente ficará disponível em alguns instantes, o ambiente está em https://$domain.conecthus.org.br/api"
  when: on_success
  only:
    - main
    - test
    - dev

notificação de falha por email:
  stage: notification
  script:
    - sendmail "$GITLAB_USER_LOGIN" "$GITLAB_USER_EMAIL" "[failed] $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME@$CI_BUILD_REF_NAME" "Olá $GITLAB_USER_LOGIN, não foi possível realizar o seu deploy. Verifique o log da pipeline para mais informações, qualquer problema entre em contato com luiz.vieira@conecthus.org.br"
  when: on_failure
  only:
    - main
    - test
    - dev
    
notificação para time de banco de dados DEV -> TEST:
  stage: notification-sgbd
  script:
    - sendmail "SGBD" "sgbd@conecthus.org.br" "[passed] $CI_PROJECT_NAMESPACE" "Atualização de ambiente feita com sucesso! Necessario atualizar base de dados de DEV --> TEST banco - $CI_PROJECT_NAMESPACE"
  when: on_success
  only:
    - test

notificação para time de banco de dados TEST -> HOM:
  stage: notification-sgbd
  script:
    - sendmail "SGBD" "sgbd@conecthus.org.br" "[passed] $CI_PROJECT_NAMESPACE" "Atualização de ambiente feita com sucesso! Necessario atualizar base de dados de TEST --> HOM banco - $CI_PROJECT_NAMESPACE"
  when: on_success
  only:
    - main